#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../src/document.h"
#include "../src/script.h"
#include "../src/layout.h"
static int checks,failures;
#define CHECK(x) do{checks++;if(!(x)){failures++;fprintf(stderr,"%d: %s\n",__LINE__,#x);}}while(0)
static browser_document *parse(const char *html){browser_document *d=calloc(1,sizeof(*d));char err[256];CHECK(browser_document_parse(d,html,strlen(html),"https://example.org/path/page","text/html",err,sizeof(err))==0);return d;}
static void drop(browser_document *d){browser_document_free(d);free(d);}
static void run(browser_document *d){char err[256];CHECK(browser_script_run(d,NULL,NULL,NULL,NULL,1000,err,sizeof(err))==0);}
static void modern(void){browser_document *d=parse("<html><head><title>old</title></head><body><p id='result'>old</p><script>const data=[1,2,3];class Message { static text(){return `modern ${data.map(x=>x*2).join(',')}`;} } let {a=4}={};document.querySelector('#result').textContent=Message.text()+' '+(2n**8n);document.title='JS works';Promise.resolve().then(()=>document.querySelector('#result').classList.add('done'));document.addEventListener('DOMContentLoaded',()=>{const p=document.createElement('p');p.textContent='loaded';document.body.append(p);});</script></body></html>");run(d);CHECK(strstr(d->text,"modern 2,4,6 256"));CHECK(strstr(d->text,"loaded"));CHECK(!strcmp(d->title,"JS works"));CHECK(d->scripts_run==1&&d->scripts_failed==0);drop(d);}
static void mutation(void){browser_document *d=parse("<body><div id='root'></div><script>const r=document.getElementById('root');r.innerHTML='<p class=note>new &amp; text</p>';r.querySelector('.note').style.color='red';r.querySelector('.note').classList.toggle('active');const a=document.createElement('a');a.href='../next';a.textContent='Continue';r.appendChild(a);setTimeout(()=>document.write('<p>timer</p>'),100);</script></body>");run(d);CHECK(strstr(d->text,"new & text"));CHECK(strstr(d->text,"timer"));CHECK(d->count==1&&!strcmp(d->links[0].url,"https://example.org/next"));CHECK(browser_style_at(d,0).color==0xff0000ff);drop(d);}
static char *fixture(void *ud,const char *url,int limit,int *len,char *err,size_t errlen){(void)ud;(void)err;(void)errlen;CHECK(!strcmp(url,"https://example.org/data"));CHECK(limit>=11);*len=11;char *p=malloc(12);memcpy(p,"{\"value\":7}",12);return p;}
static void fetching(void){browser_document *d=parse("<p id='x'>before</p><script>(async()=>{const r=await fetch('/data');const j=await r.json();document.getElementById('x').textContent='value '+j.value;})();</script>");char err[256];CHECK(browser_script_run(d,fixture,NULL,NULL,NULL,1000,err,sizeof(err))==0);CHECK(strstr(d->text,"value 7"));drop(d);d=parse("<p id='x'>before</p><script>fetch('https://other.org/data').catch(()=>document.getElementById('x').textContent='blocked');</script>");CHECK(browser_script_run(d,fixture,NULL,NULL,NULL,1000,err,sizeof(err))==0);CHECK(strstr(d->text,"blocked"));drop(d);CHECK(browser_same_origin("https://a/","https://a:443/x"));CHECK(browser_same_origin("http://a/","http://a:80/x"));CHECK(!browser_same_origin("https://a/","http://a/"));CHECK(!browser_same_origin("https://a/","https://a.evil/"));}
static char *module_fixture(void *ud,const char *url,int limit,int *len,char *err,size_t errlen){(void)ud;(void)err;(void)errlen;CHECK(!strcmp(url,"https://example.org/path/helper.js"));const char *code="export const value = 9;";*len=(int)strlen(code);CHECK(*len<limit);char *out=malloc((size_t)*len+1);strcpy(out,code);return out;}
static void modules(void){browser_document *d=parse("<p id=x>before</p><script type=module>import {value} from './helper.js';document.getElementById('x').textContent=`module ${await Promise.resolve(value)}`;</script>");char err[256];CHECK(browser_script_run(d,module_fixture,NULL,NULL,NULL,1000,err,sizeof(err))==0);CHECK(strstr(d->text,"module 9"));CHECK(d->scripts_failed==0);drop(d);}
static int cancel(void *ud){(void)ud;return 1;}
static void limits(void){char err[256];browser_document *d=parse("<p>safe</p><script>while(true){}</script>");CHECK(browser_script_run(d,NULL,NULL,NULL,NULL,30,err,sizeof(err))<0);CHECK(strstr(d->text,"safe"));CHECK(d->scripts_failed>0);drop(d);d=parse("<p>safe</p><script>while(true){}</script>");CHECK(browser_script_run(d,NULL,NULL,cancel,NULL,1000,err,sizeof(err))<0);CHECK(strstr(d->text,"safe"));drop(d);d=parse("<p>safe</p><script>const a=[];while(true)a.push('x'.repeat(10000));</script>");CHECK(browser_script_run(d,NULL,NULL,NULL,NULL,1000,err,sizeof(err))<0||d->scripts_failed>0);CHECK(strstr(d->text,"safe"));drop(d);d=parse("<p>safe</p><script>document.body.appendChild(document.body);</script>");run(d);CHECK(strstr(d->text,"safe"));CHECK(d->scripts_failed>0);drop(d);d=parse("<p>safe</p><script type=module>import x from '/x.js';</script>");run(d);CHECK(d->scripts_failed>0);drop(d);}
static void styling(void){browser_document *d=parse("<style>p{color:blue}div .note{color:red}#x{color:green}p{color:yellow!important}.gone{display:none}</style><body><div><p id=x class=note style='color:white'>visible</p><p class=gone>secret</p></div></body>");CHECK(!strstr(d->text,"secret"));CHECK(browser_style_at(d,0).color==0xff00ffff);drop(d);d=parse("<style>@media screen {@media screen {p{color:#123456}}}p{font-size:24px;text-align:center}</style><p>center</p>");browser_style st=browser_style_at(d,0);CHECK(st.color==0xff563412);CHECK(st.align==1&&st.scale>0.9f);drop(d);char css[4096]="";for(int i=0;i<100;i++)strcat(css,"@media screen {");strcat(css,"p{color:red}");for(int i=0;i<100;i++)strcat(css,"}");browser_css rules={0};CHECK(css_add(&rules,css,strlen(css))==0);CHECK(rules.omitted);css_free(&rules);}
typedef struct{const char *s;size_t pos,len;int chunk;} reader;
static int reading(void *ud,char *out,size_t max){reader *r=ud;size_t n=r->len-r->pos;if(n>max)n=max;if(n>(size_t)r->chunk)n=(size_t)r->chunk;memcpy(out,r->s+r->pos,n);r->pos+=n;return (int)n;}
static void streaming(void){const char *html="<!--hidden--><p>α &amp; β 😀</p><script>if(1<2)document.write('ok')</script><p>tail</p>";char err[256];for(int chunk=1;chunk<18;chunk++){reader r={html,0,strlen(html),chunk};browser_document *d=calloc(1,sizeof(*d));CHECK(browser_document_read(d,reading,&r,"https://example.org/","text/html",NULL,NULL,err,sizeof(err))==0);CHECK(strstr(d->text,"α & β 😀"));CHECK(strstr(d->text,"tail"));drop(d);}size_t n=2*1024*1024;char *large=malloc(n+100);strcpy(large,"<script>");memset(large+8,' ',n);strcpy(large+8+n,"</script><p>tail after huge script</p>");reader r={large,0,strlen(large),113};browser_document *d=calloc(1,sizeof(*d));CHECK(browser_document_read(d,reading,&r,"https://example.org/","text/html",NULL,NULL,err,sizeof(err))==0);CHECK(strstr(d->text,"tail after huge script"));CHECK(!d->dom->nodes[1].text||*dom_attr(&d->dom->nodes[1],"data-ark-omitted"));drop(d);free(large);browser_dom dom;const char *cycle="[{\"tag\":\"#document\",\"text\":\"\",\"attrs\":{},\"children\":[0]}]";CHECK(dom_from_json(&dom,cycle,strlen(cycle))<0);}
static void spans(void){browser_document *d=parse("<pre><span style='color:red'>a </span><span style='color:blue'>  </span></pre><p style='color:green'>b</p>");for(int i=1;i<d->span_count;i++)CHECK(d->spans[i].offset>=d->spans[i-1].offset);const char *b=strchr(d->text,'b');CHECK(b&&browser_style_at(d,(size_t)(b-d->text)).color==0xff008000);drop(d);}
static float measure(void *ud,const char *s,size_t n,browser_style style){(void)ud;(void)s;(void)n;return style.scale*10;}
static void layout(void){browser_document *d=parse("<p>one two αβγδε long</p>");browser_line lines[32];int count=browser_layout(d,lines,32,30,measure,NULL);CHECK(count>2);for(int i=0;i<count;i++){CHECK(lines[i].length>0);CHECK(((unsigned char)d->text[lines[i].start]&0xc0)!=0x80);CHECK(lines[i].height>=11);}drop(d);}
int main(void){modern();mutation();fetching();modules();limits();styling();streaming();spans();layout();printf("engine: %d checks, %d failures\n",checks,failures);return failures?1:0;}
